export const Country = {
  ASIA: ["KOREA", "JAPAN", "THAILAND", "MONGOLIA", "NEPAL"],
  EUROPE: ["FRANCE", "SWEDEN", "SWITZERLAND", "NORWAY", "UNITED KINGDOM", "CROATIA"],
  AFRICA: ["SOUTH AFRICA", "KENYA", "NAMIBIA", "TANZANIA", "UGANDA"],
  OCEANIA: ["NEW ZEALAND", "AUSTRALIA", "FIJI", "NEW CALEDONIA"],
  AMERICA: ["UNITED STATES", "CANADA", "COSTA RICA", "CHILE", "BRAZIL"],
}
