import Core from "@/libs/layout/Core";
import Provider from "@/libs/layout/Provider";
import { ReactQueryClientProvider } from "@/libs/layout/ReactQueryClientProvider";

export const metadata = {
  title: "OvCams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryClientProvider>
      <html>
        <body>
          <Provider>{children}</Provider>
          <Core />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
