import Core from "@/libs/layouts/Core"
import Provider from "@/libs/layouts/providers/Provider"
import { ReactQueryClientProvider } from "@/libs/layouts/providers/ReactQueryClientProvider"
import { AuthModalStoreContextProvider } from "@/libs/layouts/providers/AuthModalStoreContextProvider"
import { ContinentStoreContextProvider } from "@/libs/layouts/providers/ContinentStoreContextProvider"
import { IChildren } from "@/libs/types"
import { Suspense } from "react"

export const metadata = {
  title: "OvCams",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: IChildren) {
  return (
    <ReactQueryClientProvider>
      <html>
        <body>
          <Suspense>
            <AuthModalStoreContextProvider>
              <ContinentStoreContextProvider>
                <Provider>{children}</Provider>
                <Core />
              </ContinentStoreContextProvider>
            </AuthModalStoreContextProvider>
          </Suspense>
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}
