import Core from "@/libs/layouts/Core";
import Provider from "@/libs/layouts/providers/Provider";
import { ReactQueryClientProvider } from "@/libs/layouts/providers/ReactQueryClientProvider";
import { AuthModalStoreContextProvider } from "@/libs/layouts/providers/AuthModalStoreContextProvider";

export const metadata = {
  title: "OvCams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryClientProvider>
      <html>
        <body>
          <AuthModalStoreContextProvider>
            <Provider>{children}</Provider>
            <Core />
          </AuthModalStoreContextProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
